name: CI

on: push

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p build
          go build -o build/OpenGFW-${GOOS}-${GOARCH} -ldflags "-s -w" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenGFW
          path: |
            build/
          
